variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'any cpu'

trigger: none
pr:
  branches:
    include:
    - releases

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 3.1.102'
  inputs:
    version: 3.1.102


- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: 'WebApplication1/WebApplication1.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: 'WebApplication1/WebApplication1.csproj'
    arguments: '--configuration $(BuildConfiguration)'


- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
